/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getStoreInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'name' : IDL.Text,
          'address' : IDL.Text,
          'timings' : IDL.Text,
        }),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStoreInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'name' : IDL.Text,
            'address' : IDL.Text,
            'timings' : IDL.Text,
          }),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };